### ISSUE TITLE
Issue with RSSI calculation

### ISSUE THREAD

**Issue by E2w4UmWh** [newracom/nrc7292_sdk#3]
Hi,
I'm using standalone-mode with the precompiled binary ATCMD_UART from: https://github.com/newracom/nrc7292_sdk/tree/master/package/standalone/atcmd_binary

It seems that TX-Power switching does not work, at least at STAs.
I'm running the following AT-command sequence at STA:
AT+WTXPOWER=1
AT+WTXPOWER=11
AT+WTXPOWER=21
AT+WTXPOWER=30
Each answered with ok.

After each AT+WTXPOWER, I send an AT+WSTAINFO? at the AP. The response is as follwos:
+WSTAINFO:1,"00:c0:ca:ae:d5:9c",-38,32,6
OK
+WSTAINFO:1,"00:c0:ca:ae:d5:9c",-38,32,6
OK
+WSTAINFO:1,"00:c0:ca:ae:d5:9c",-38,32,6
OK
+WSTAINFO:1,"00:c0:ca:ae:d5:9c",-38,32,6
OK

I would have expected significant changes of the RSSI value from -38 to -9 dBm.  

Sending a Ping from AP to STA however, changes the result of WSTAINFO (performad at AP):

+WEVENT:"PING",64,"192.168.200.2",1,255,9
+WEVENT:"PING",64,"192.168.200.2",2,255,5
+WEVENT:"PING",64,"192.168.200.2",3,255,8
+WEVENT:"PING",64,"192.168.200.2",4,255,22
+WEVENT:"PING",64,"192.168.200.2",5,255,5
OK
+WSTAINFO:1,"00:c0:ca:ae:d5:9c",-10,29,4
OK

Now, I doget -10, which is surprisingly close to the estimated  -10 dBm.

I think there is an issue with updating the RSSI value in the STA-frimware, or is that normal behaviour?
I would appreciate any information or clarification.

**Comment by newracom** [comment]
Dear @E2w4UmWh,

Thank you for your inquiry.

First of all, RSSI value is updated when the device receives any frame.
So, STA's RSSI can be continuously updated because of beacon frames from AP,
but AP's RSSI requires the help of uplink traffic like ping from STA.

We used the attached script files and ran them on AP and STA as below.

**[AT-CMD SoftAP]**
`$ sudo ./raspi-atcmd-cli -U -s wifi-softap-open-dhcps`

**[AT-CMD STA]**
`$ sudo ./raspi-atcmd-cli -U -s wifi-connect-open-dhcp`

And we found that RSSI values of AP followed the TX power of STA.
Please refer to the scripts and test logs.

Best regards,
Newracom

* script and log files: [nrc7292_sdk_issue3_support_files.zip](https://github.com/newracom/nrc7292_sdk/files/7961109/nrc7292_sdk_issue3_support_files.zip)

**Comment by E2w4UmWh** [comment]
Thank you very much for the explanation, that helped to understand what happens on the MAC layer!
Comming from other radio technologies, I'm no t that much confident with WiFi on the RF protocol-side.

Transmitting a ping from STA to AP does indeed change the RSSI-value, when applying AT+STAINFO on the AP.
The results in dBm are not always correlatad with the TX-power-difference in dBm applied, on the STA, but sometimes I observed different values of the MCS_index as well, which might be part of RSSI calculation???

Some of my observations:
STA-TX-pwr dBm //  STAINFO (AP) // comment
3 // +WSTAINFO:1,"00:c0:ca:ae:d5:9c",-34,32,5
6 // +WSTAINFO:1,"00:c0:ca:ae:d5:9c",-36,30,5
12 // +WSTAINFO:1,"00:c0:ca:ae:d5:9c",-11,30,5 //+ 6dB TX pwr resulting in +25 dB RSSI?
12 // +WSTAINFO:1,"00:c0:ca:ae:d5:9c",-15,32,5 // some signal fading?
18 // +WSTAINFO:1,"00:c0:ca:ae:d5:9c",-6,32,5
24 // +WSTAINFO:1,"00:c0:ca:ae:d5:9c",-3,28,4 // MCS_index has changed!

Thanks for your quick response and clarification!!!

**Comment by newracom** [comment]
Dear @E2w4UmWh,

Thank you for your information.
NRC7292 SW has rate adaptation mechanism inside, 
so it adaptively changes its MCS index based on its quality of transmission.
The MCS index change could happen due to the poor RSSI of peer device and corresponding poor quality of transmission,
but there is no direct relationship between MCS index and RSSI value.

Best regards,
Newracom
